---
# 1. Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-notification-service
spec:
  ports:
    - port: 6379
  selector:
    app: redis
---
# 2. Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
# 3. Postgres Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-notification
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
# 4. Postgres Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: notification-env-secret
                  key: QUARKUS_DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-env-secret
                  key: QUARKUS_DATASOURCE_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: notification-env-secret
                  key: QUARKUS_DATASOURCE_DB